#开发环境
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.169.200:1521:orcl
    username: K_TEST
    password: K_TEST_9
    initialSize: 1
    minIdle: 1
    maxActive: 20
  #thymeleaf模板引擎
  thymeleaf:
    cache: false
  redis:
      host: 192.168.169.200
      port: 6378
      password: myRedis
      database: 3

  session:
      store-type: redis
#web服务器端口
server:
  port: 8866





